FROM maven:3.8.3-eclipse-temurin-17 as build

WORKDIR /app

COPY pom.xml .
COPY src src

RUN --mount=type=cache,id=mvncache,target=/root/.m2/repository,rw \
	mvn -B package

FROM debian:bullseye-20211011-slim
COPY --from=build /app/target/jlink-image /app
ENTRYPOINT ["/app/bin/myapp"]
